# Reproducible workflow for the PTB_GWAS project with step-scoped experiments.
import os


# 1. Fetch flat configuration values 

# Parse the sample names directly from the file

with open(config["sample_list"]) as f:
    SAMPLES = [line.strip() for line in f if line.strip()]

ASSEMBLY_DIR = config["assembly_dir"]
ANNOTATION_DIR = config["annotation_dir"]
FASTA_EXTENSION = config["fasta_extension"]

rule all:
    input:
        expand(f"{ANNOTATION_DIR}/{{isolate}}_bakta/{{isolate}}.gff3", isolate=SAMPLES)#,

# ANNOTATION AND QC ——————————————————————————————————————————————————————————————


rule annotation_isolate:
    input:
        ancient(f"{ASSEMBLY_DIR}/{{isolate}}{FASTA_EXTENSION}"), 
    output:
        f"{ANNOTATION_DIR}/{{isolate}}_bakta/{{isolate}}.gff3",
    params:
        out_dir = f"{ANNOTATION_DIR}/{{isolate}}_bakta",
        prefix =f"{{isolate}}",
        bakta_db = config["bakta_database"]
    conda:
        "genomics_env"
    threads: 4
    shell:
        r'''
        mkdir -p $(dirname {output})
        bakta --db {params.bakta_db} -o {params.out_dir} --prefix {params.prefix} --locus-tag {params.prefix} --threads {threads} {input} --keep-contig-headers --force
        '''

